remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

title: Vishal Sonawane
tagline: Lead Software Engineer | Python | AWS | Data
description: Career website and resume of Vishal Sonawane.

minimal_mistakes_skin: default

author:
  name: "Vishal Sonawane"
  bio: "Lead Software Engineer"
  location: "Pune, India"
  email: "vishalsonawane1515@gmail.com"
  links:
    - label: "GitHub"
      url: "https://github.com/vishal-sonawane"